name: Branch Protection Setup

on:
  workflow_dispatch:
  schedule:
    # Run weekly to ensure protection rules are maintained
    - cron: '0 2 * * 1'

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure branch protection for main
        run: |
          echo "Setting up branch protection rules for main branch..."
          
          # Main branch protection
          gh api repos/${{ github.repository }}/branches/main/protection \
            --method PUT \
            --field required_status_checks='{
              "strict": true,
              "contexts": [
                "backend-tests",
                "frontend-tests", 
                "security-scan",
                "docker-build"
              ]
            }' \
            --field enforce_admins=true \
            --field required_pull_request_reviews='{
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true,
              "required_approving_review_count": 2,
              "require_last_push_approval": true
            }' \
            --field restrictions='null' \
            --field required_linear_history=true \
            --field allow_force_pushes=false \
            --field allow_deletions=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure branch protection for develop
        run: |
          echo "Setting up branch protection rules for develop branch..."
          
          # Develop branch protection (lighter rules)
          gh api repos/${{ github.repository }}/branches/develop/protection \
            --method PUT \
            --field required_status_checks='{
              "strict": true,
              "contexts": [
                "backend-tests",
                "frontend-tests"
              ]
            }' \
            --field enforce_admins=false \
            --field required_pull_request_reviews='{
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false,
              "required_approving_review_count": 1
            }' \
            --field restrictions='null' \
            --field required_linear_history=false \
            --field allow_force_pushes=false \
            --field allow_deletions=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Verify protection rules
        run: |
          echo "Verifying branch protection rules..."
          
          echo "Main branch protection:"
          gh api repos/${{ github.repository }}/branches/main/protection | jq '.'
          
          echo "Develop branch protection:"
          gh api repos/${{ github.repository }}/branches/develop/protection | jq '.'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}